from extract import Extractor
import pandas as pd

class Covid19Extractor(Extractor):
    def __init__(self):
        super().__init__()

    def try_extract(self, path: str) -> pd.DataFrame | bool:
        df = pd.read_csv(path)
        needed_columns = ["Country/Region", "Date", "Confirmed", "Deaths"]
        if any(col not in df.columns for col in needed_columns):
            return False

        # Filter out unneeded columns
        df = df[needed_columns]

        # Rename columns for consistency
        df = df.rename(columns={
            "Country/Region": "country",
            "Date": "date",
            "Confirmed": "total_cases",
            "Deaths": "total_deaths",
        })

        # Parse date column
        df['date'] = pd.to_datetime(df['date'])

        # Now that Province/State is not a thing, we need to merge together countries with the same name
        df = df.groupby(["country", "date"]).sum().reset_index()

        # Ensure data is sorted by country and date (needed for calculating new cases/deaths)
        df = df.sort_values(by=["country", "date"])

        # Calculate new_cases and new_deaths
        df["new_cases"] = df.groupby("country")["total_cases"].diff().fillna(0).astype(int)
        df["new_deaths"] = df.groupby("country")["total_deaths"].diff().fillna(0).astype(int)

        # Map each country to a continent and ISO3 code
        df = df[df["country"].map(location_mapping).apply(lambda x: isinstance(x, dict)).astype(bool)]
        df[["continent", "country"]] = df["country"].map(location_mapping).apply(pd.Series)
        df["iso_code"] = df["country"].map(country_to_iso3)
        # Add pandemic metadata
        df["pandemic"] = "covid-19"
        df["pandemic_pathogen"] = "SARS-CoV-2"
        df["pandemic_start_date"] = "2019-12-01"
        df["pandemic_end_date"] = "2023-07-01"
        # Add population column (set to None for now)
        df["population"] = None

        return df

location_mapping = {
    "Afghanistan": {"continent": "ASIA", "country": "Afghanistan"},
    "Albania": {"continent": "EUROPE", "country": "Albania"},
    "Algeria": {"continent": "AFRICA", "country": "Algeria"},
    "Andorra": {"continent": "EUROPE", "country": "Andorra"},
    "Angola": {"continent": "AFRICA", "country": "Angola"},
    "Antigua and Barbuda": {"continent": "NORTH_AMERICA", "country": "Antigua and Barbuda"},
    "Argentina": {"continent": "SOUTH_AMERICA", "country": "Argentina"},
    "Armenia": {"continent": "ASIA", "country": "Armenia"},
    "Australia": {"continent": "OCEANIA", "country": "Australia"},
    "Austria": {"continent": "EUROPE", "country": "Austria"},
    "Azerbaijan": {"continent": "ASIA", "country": "Azerbaijan"},
    "Bahamas": {"continent": "NORTH_AMERICA", "country": "Bahamas"},
    "Bahrain": {"continent": "ASIA", "country": "Bahrain"},
    "Bangladesh": {"continent": "ASIA", "country": "Bangladesh"},
    "Barbados": {"continent": "NORTH_AMERICA", "country": "Barbados"},
    "Belarus": {"continent": "EUROPE", "country": "Belarus"},
    "Belgium": {"continent": "EUROPE", "country": "Belgium"},
    "Benin": {"continent": "AFRICA", "country": "Benin"},
    "Bhutan": {"continent": "ASIA", "country": "Bhutan"},
    "Bolivia": {"continent": "SOUTH_AMERICA", "country": "Bolivia"},
    "Bosnia and Herzegovina": {"continent": "EUROPE", "country": "Bosnia and Herzegovina"},
    "Brazil": {"continent": "SOUTH_AMERICA", "country": "Brazil"},
    "Brunei": {"continent": "ASIA", "country": "Brunei"},
    "Bulgaria": {"continent": "EUROPE", "country": "Bulgaria"},
    "Burkina Faso": {"continent": "AFRICA", "country": "Burkina Faso"},
    "Cabo Verde": {"continent": "AFRICA", "country": "Cabo Verde"},
    "Cambodia": {"continent": "ASIA", "country": "Cambodia"},
    "Cameroon": {"continent": "AFRICA", "country": "Cameroon"},
    "Canada": {"continent": "NORTH_AMERICA", "country": "Canada"},
    "Central African Republic": {"continent": "AFRICA", "country": "Central African Republic"},
    "Chad": {"continent": "AFRICA", "country": "Chad"},
    "Chile": {"continent": "SOUTH_AMERICA", "country": "Chile"},
    "China": {"continent": "ASIA", "country": "China"},
    "Colombia": {"continent": "SOUTH_AMERICA", "country": "Colombia"},
    "Congo (Brazzaville)": {"continent": "AFRICA", "country": "Republic of the Congo"},
    "Congo (Kinshasa)": {"continent": "AFRICA", "country": "Democratic Republic of the Congo"},
    "Costa Rica": {"continent": "NORTH_AMERICA", "country": "Costa Rica"},
    "Cote d'Ivoire": {"continent": "AFRICA", "country": "Cote d'Ivoire"},
    "Croatia": {"continent": "EUROPE", "country": "Croatia"},
    "Cuba": {"continent": "NORTH_AMERICA", "country": "Cuba"},
    "Cyprus": {"continent": "EUROPE", "country": "Cyprus"},
    "Czechia": {"continent": "EUROPE", "country": "Czechia"},
    "Denmark": {"continent": "EUROPE", "country": "Denmark"},
    "Djibouti": {"continent": "AFRICA", "country": "Djibouti"},
    "Dominican Republic": {"continent": "NORTH_AMERICA", "country": "Dominican Republic"},
    "Ecuador": {"continent": "SOUTH_AMERICA", "country": "Ecuador"},
    "Egypt": {"continent": "AFRICA", "country": "Egypt"},
    "El Salvador": {"continent": "NORTH_AMERICA", "country": "El Salvador"},
    "Equatorial Guinea": {"continent": "AFRICA", "country": "Equatorial Guinea"},
    "Eritrea": {"continent": "AFRICA", "country": "Eritrea"},
    "Estonia": {"continent": "EUROPE", "country": "Estonia"},
    "Eswatini": {"continent": "AFRICA", "country": "Eswatini"},
    "Ethiopia": {"continent": "AFRICA", "country": "Ethiopia"},
    "Fiji": {"continent": "OCEANIA", "country": "Fiji"},
    "Finland": {"continent": "EUROPE", "country": "Finland"},
    "France": {"continent": "EUROPE", "country": "France"},
    "Gabon": {"continent": "AFRICA", "country": "Gabon"},
    "Gambia": {"continent": "AFRICA", "country": "Gambia"},
    "Georgia": {"continent": "ASIA", "country": "Georgia"},
    "Germany": {"continent": "EUROPE", "country": "Germany"},
    "Ghana": {"continent": "AFRICA", "country": "Ghana"},
    "Greece": {"continent": "EUROPE", "country": "Greece"},
    "Grenada": {"continent": "NORTH_AMERICA", "country": "Grenada"},
    "Guatemala": {"continent": "NORTH_AMERICA", "country": "Guatemala"},
    "Guinea": {"continent": "AFRICA", "country": "Guinea"},
    "Guinea-Bissau": {"continent": "AFRICA", "country": "Guinea-Bissau"},
    "Guyana": {"continent": "SOUTH_AMERICA", "country": "Guyana"},
    "Haiti": {"continent": "NORTH_AMERICA", "country": "Haiti"},
    "Holy See": {"continent": "EUROPE", "country": "Holy See"},
    "Honduras": {"continent": "NORTH_AMERICA", "country": "Honduras"},
    "Hungary": {"continent": "EUROPE", "country": "Hungary"},
    "Iceland": {"continent": "EUROPE", "country": "Iceland"},
    "India": {"continent": "ASIA", "country": "India"},
    "Indonesia": {"continent": "ASIA", "country": "Indonesia"},
    "Iran": {"continent": "ASIA", "country": "Iran"},
    "Iraq": {"continent": "ASIA", "country": "Iraq"},
    "Ireland": {"continent": "EUROPE", "country": "Ireland"},
    "Israel": {"continent": "ASIA", "country": "Israel"},
    "Italy": {"continent": "EUROPE", "country": "Italy"},
    "Jamaica": {"continent": "NORTH_AMERICA", "country": "Jamaica"},
    "Japan": {"continent": "ASIA", "country": "Japan"},
    "Jordan": {"continent": "ASIA", "country": "Jordan"},
    "Kazakhstan": {"continent": "ASIA", "country": "Kazakhstan"},
    "Kenya": {"continent": "AFRICA", "country": "Kenya"},
    "South Korea": {"continent": "ASIA", "country": "South Korea"},
    "Kuwait": {"continent": "ASIA", "country": "Kuwait"},
    "Kyrgyzstan": {"continent": "ASIA", "country": "Kyrgyzstan"},
    "Latvia": {"continent": "EUROPE", "country": "Latvia"},
    "Lebanon": {"continent": "ASIA", "country": "Lebanon"},
    "Liberia": {"continent": "AFRICA", "country": "Liberia"},
    "Liechtenstein": {"continent": "EUROPE", "country": "Liechtenstein"},
    "Lithuania": {"continent": "EUROPE", "country": "Lithuania"},
    "Luxembourg": {"continent": "EUROPE", "country": "Luxembourg"},
    "Madagascar": {"continent": "AFRICA", "country": "Madagascar"},
    "Malaysia": {"continent": "ASIA", "country": "Malaysia"},
    "Maldives": {"continent": "ASIA", "country": "Maldives"},
    "Malta": {"continent": "EUROPE", "country": "Malta"},
    "Mauritania": {"continent": "AFRICA", "country": "Mauritania"},
    "Mauritius": {"continent": "AFRICA", "country": "Mauritius"},
    "Mexico": {"continent": "NORTH_AMERICA", "country": "Mexico"},
    "Moldova": {"continent": "EUROPE", "country": "Moldova"},
    "Monaco": {"continent": "EUROPE", "country": "Monaco"},
    "Mongolia": {"continent": "ASIA", "country": "Mongolia"},
    "Montenegro": {"continent": "EUROPE", "country": "Montenegro"},
    "Morocco": {"continent": "AFRICA", "country": "Morocco"},
    "Namibia": {"continent": "AFRICA", "country": "Namibia"},
    "Nepal": {"continent": "ASIA", "country": "Nepal"},
    "Netherlands": {"continent": "EUROPE", "country": "Netherlands"},
    "New Zealand": {"continent": "OCEANIA", "country": "New Zealand"},
    "Nicaragua": {"continent": "NORTH_AMERICA", "country": "Nicaragua"},
    "Niger": {"continent": "AFRICA", "country": "Niger"},
    "Nigeria": {"continent": "AFRICA", "country": "Nigeria"},
    "North Macedonia": {"continent": "EUROPE", "country": "North Macedonia"},
    "Norway": {"continent": "EUROPE", "country": "Norway"},
    "Oman": {"continent": "ASIA", "country": "Oman"},
    "Pakistan": {"continent": "ASIA", "country": "Pakistan"},
    "Panama": {"continent": "NORTH_AMERICA", "country": "Panama"},
    "Papua New Guinea": {"continent": "OCEANIA", "country": "Papua New Guinea"},
    "Paraguay": {"continent": "SOUTH_AMERICA", "country": "Paraguay"},
    "Peru": {"continent": "SOUTH_AMERICA", "country": "Peru"},
    "Philippines": {"continent": "ASIA", "country": "Philippines"},
    "Poland": {"continent": "EUROPE", "country": "Poland"},
    "Portugal": {"continent": "EUROPE", "country": "Portugal"},
    "Qatar": {"continent": "ASIA", "country": "Qatar"},
    "Romania": {"continent": "EUROPE", "country": "Romania"},
    "Russia": {"continent": "EUROPE", "country": "Russia"},
    "Rwanda": {"continent": "AFRICA", "country": "Rwanda"},
    "Saint Lucia": {"continent": "NORTH_AMERICA", "country": "Saint Lucia"},
    "Saint Vincent and the Grenadines": {"continent": "NORTH_AMERICA", "country": "Saint Vincent and the Grenadines"},
    "San Marino": {"continent": "EUROPE", "country": "San Marino"},
    "Saudi Arabia": {"continent": "ASIA", "country": "Saudi Arabia"},
    "Senegal": {"continent": "AFRICA", "country": "Senegal"},
    "Serbia": {"continent": "EUROPE", "country": "Serbia"},
    "Seychelles": {"continent": "AFRICA", "country": "Seychelles"},
    "Singapore": {"continent": "ASIA", "country": "Singapore"},
    "Slovakia": {"continent": "EUROPE", "country": "Slovakia"},
    "Slovenia": {"continent": "EUROPE", "country": "Slovenia"},
    "Somalia": {"continent": "AFRICA", "country": "Somalia"},
    "South Africa": {"continent": "AFRICA", "country": "South Africa"},
    "Spain": {"continent": "EUROPE", "country": "Spain"},
    "Sri Lanka": {"continent": "ASIA", "country": "Sri Lanka"},
    "Sudan": {"continent": "AFRICA", "country": "Sudan"},
    "Suriname": {"continent": "SOUTH_AMERICA", "country": "Suriname"},
    "Sweden": {"continent": "EUROPE", "country": "Sweden"},
    "Switzerland": {"continent": "EUROPE", "country": "Switzerland"},
    "Taiwan*": {"continent": "ASIA", "country": "Taiwan"},
    "Tanzania": {"continent": "AFRICA", "country": "Tanzania"},
    "Thailand": {"continent": "ASIA", "country": "Thailand"},
    "Togo": {"continent": "AFRICA", "country": "Togo"},
    "Trinidad and Tobago": {"continent": "NORTH_AMERICA", "country": "Trinidad and Tobago"},
    "Tunisia": {"continent": "AFRICA", "country": "Tunisia"},
    "Turkey": {"continent": "ASIA", "country": "Turkey"},
    "Uganda": {"continent": "AFRICA", "country": "Uganda"},
    "Ukraine": {"continent": "EUROPE", "country": "Ukraine"},
    "United Arab Emirates": {"continent": "ASIA", "country": "United Arab Emirates"},
    "United Kingdom": {"continent": "EUROPE", "country": "United Kingdom"},
    "US": {"continent": "NORTH_AMERICA", "country": "United States"},
    "Uruguay": {"continent": "SOUTH_AMERICA", "country": "Uruguay"},
    "Uzbekistan": {"continent": "ASIA", "country": "Uzbekistan"},
    "Venezuela": {"continent": "SOUTH_AMERICA", "country": "Venezuela"},
    "Vietnam": {"continent": "ASIA", "country": "Vietnam"},
    "Zambia": {"continent": "AFRICA", "country": "Zambia"},
    "Zimbabwe": {"continent": "AFRICA", "country": "Zimbabwe"},
    "Dominica": {"continent": "NORTH_AMERICA", "country": "Dominica"},
    "Mozambique": {"continent": "AFRICA", "country": "Mozambique"},
    "Syria": {"continent": "ASIA", "country": "Syria"},
    "Timor-Leste": {"continent": "ASIA", "country": "Timor-Leste"},
    "Belize": {"continent": "NORTH_AMERICA", "country": "Belize"},
    "Laos": {"continent": "ASIA", "country": "Laos"},
    "Libya": {"continent": "AFRICA", "country": "Libya"},
    "West Bank and Gaza": {"continent": "ASIA", "country": "West Bank and Gaza"},
    "Mali": {"continent": "AFRICA", "country": "Mali"},
    "Saint Kitts and Nevis": {"continent": "NORTH_AMERICA", "country": "Saint Kitts and Nevis"},
    "Kosovo": {"continent": "EUROPE", "country": "Kosovo"},
    "Burma": {"continent": "ASIA", "country": "Myanmar"},
    "Botswana": {"continent": "AFRICA", "country": "Botswana"},
    "Burundi": {"continent": "AFRICA", "country": "Burundi"},
    "Sierra Leone": {"continent": "AFRICA", "country": "Sierra Leone"},
    "Malawi": {"continent": "AFRICA", "country": "Malawi"},
    "South Sudan": {"continent": "AFRICA", "country": "South Sudan"},
    "Western Sahara": {"continent": "AFRICA", "country": "Western Sahara"},
    "Sao Tome and Principe": {"continent": "AFRICA", "country": "Sao Tome and Principe"},
    "Yemen": {"continent": "ASIA", "country": "Yemen"},
    "Comoros": {"continent": "AFRICA", "country": "Comoros"},
    "Tajikistan": {"continent": "ASIA", "country": "Tajikistan"},
    "Lesotho": {"continent": "AFRICA", "country": "Lesotho"},
}

country_to_iso3 = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "DZA",
    "Andorra": "AND",
    "Angola": "AGO",
    "Antigua and Barbuda": "ATG",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas": "BHS",
    "Bahrain": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Bhutan": "BTN",
    "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA",
    "Brunei": "BRN",
    "Bulgaria": "BGR",
    "Burkina Faso": "BFA",
    "Cabo Verde": "CPV",
    "Cambodia": "KHM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Central African Republic": "CAF",
    "Chad": "TCD",
    "Chile": "CHL",
    "China": "CHN",
    "Colombia": "COL",
    "Republic of the Congo": "COG",
    "Democratic Republic of the Congo": "COD",
    "Costa Rica": "CRI",
    "Cote d'Ivoire": "CIV",
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Denmark": "DNK",
    "Djibouti": "DJI",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    "Equatorial Guinea": "GNQ",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Eswatini": "SWZ",
    "Ethiopia": "ETH",
    "Fiji": "FJI",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia": "GMB",
    "Georgia": "GEO",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Guatemala": "GTM",
    "Guinea": "GIN",
    "Guinea-Bissau": "GNB",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Holy See": "VAT",
    "Honduras": "HND",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "South Korea": "KOR",
    "Kuwait": "KWT",
    "Kyrgyzstan": "KGZ",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Liberia": "LBR",
    "Liechtenstein": "LIE",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Madagascar": "MDG",
    "Malaysia": "MYS",
    "Maldives": "MDV",
    "Malta": "MLT",
    "Mauritania": "MRT",
    "Mauritius": "MUS",
    "Mexico": "MEX",
    "Moldova": "MDA",
    "Monaco": "MCO",
    "Mongolia": "MNG",
    "Montenegro": "MNE",
    "Morocco": "MAR",
    "Namibia": "NAM",
    "Nepal": "NPL",
    "Netherlands": "NLD",
    "New Zealand": "NZL",
    "Nicaragua": "NIC",
    "Niger": "NER",
    "Nigeria": "NGA",
    "North Macedonia": "MKD",
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Philippines": "PHL",
    "Poland": "POL",
    "Portugal": "PRT",
    "Qatar": "QAT",
    "Romania": "ROU",
    "Russia": "RUS",
    "Rwanda": "RWA",
    "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VCT",
    "San Marino": "SMR",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Seychelles": "SYC",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Somalia": "SOM",
    "Mali": "MLI",
    "South Africa": "ZAF",
    "Spain": "ESP",
    "Sri Lanka": "LKA",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Thailand": "THA",
    "Togo": "TGO",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "United States": "USA",
    "Uruguay": "URY",
    "Uzbekistan": "UZB",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
    "Dominica": "DMA",
    "Mozambique": "MOZ",
    "Syria": "SYR",
    "Timor-Leste": "TLS",
    "Belize": "BLZ",
    "Laos": "LAO",
    "Libya": "LBY",
    "West Bank and Gaza": "PSE",
    "Saint Kitts and Nevis": "KNA",
    "Kosovo": "XKX",
    "Myanmar": "MMR",
    "Botswana": "BWA",
    "Burundi": "BDI",
    "Sierra Leone": "SLE",
    "Malawi": "MWI",
    "South Sudan": "SSD",
    "Western Sahara": "ESH",
    "Sao Tome and Principe": "STP",
    "Yemen": "YEM",
    "Comoros": "COM",
    "Tajikistan": "TJK",
    "Lesotho": "LSO",
}
